### ISSUE TITLE
Monitor error during delete

### ISSUE THREAD

**Issue by nicfit** [nicfit/MishMash#111]
```
D=(1) MASK=(1073742080) MASK->NAMES=['IN_CREATE', 'IN_ISDIR'] WATCH-PATH=/media/music FILENAME=Beach Boys, The
unsonic.nicfit.net    | WD=(1) MASK=(1073741828) MASK->NAMES=['IN_ATTRIB', 'IN_ISDIR'] WATCH-PATH=/media/music FILENAME=Beach Boys, The
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 15 - Hang On To Your Ego.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 12 - Pet Sounds.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 02 - You Still Believe In Me.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 13 - Caroline No.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=cover.jpg
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 03 - That's Not Me.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 07 - Sloop John B..mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 09 - I Know There's An Answer.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 16 - Trombone Dixie.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 06 - Let's Go Away For Awhile.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 08 - God Only Knows.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 05 - I'm Waiting For The Day.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 04 - Don't Talk (Put Your Head On My Shoulders).mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 14 - Unreleased Backgrounds.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media/Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 11 - I Just Wasn't Made For These Times.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media//Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 10 - Here Today.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(512) MASK->NAMES=['IN_DELETE'] WATCH-PATH=/media//Beach Boys, The/1966 - Pet Sounds FILENAME=The Beach Boys - 01 - Wouldn't It Be Nice.mp3
unsonic.nicfit.net    | WD=(3570) MASK=(1024) MASK->NAMES=['IN_DELETE_SELF'] WATCH-PATH=/media//Beach Boys, The/1966 - Pet Sounds FILENAME=.
unsonic.nicfit.net    | WD=(3570) MASK=(32768) MASK->NAMES=['IN_IGNORED'] WATCH-PATH=/media//Beach Boys, The/1966 - Pet Sounds FILENAME=.
unsonic.nicfit.net    | WD=(3571) MASK=(1073742336) MASK->NAMES=['IN_DELETE', 'IN_ISDIR'] WATCH-PATH=/media//Beach Boys, The FILENAME=1966 - Pet Sounds
unsonic.nicfit.net    | Process Monitor-1:
unsonic.nicfit.net    | Traceback (most recent call last):
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/mishmash/commands/sync/_inotify.py", line 84, in _main
unsonic.nicfit.net    |     str(watch_path).encode(LOCAL_FS_ENCODING))
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/inotify/adapters.py", line 90, in remove_watch
unsonic.nicfit.net    |     inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/inotify/calls.py", line 35, in _check_nonnegative
unsonic.nicfit.net    |     (result,))
unsonic.nicfit.net    | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
unsonic.nicfit.net    | 
unsonic.nicfit.net    | During handling of the above exception, another exception occurred:
unsonic.nicfit.net    | 
unsonic.nicfit.net    | Traceback (most recent call last):
unsonic.nicfit.net    |   File "/usr/lib64/python3.6/multiprocessing/process.py", line 249, in _bootstrap
unsonic.nicfit.net    |     self.run()
unsonic.nicfit.net    |   File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
unsonic.nicfit.net    |     self._target(*self._args, **self._kwargs)
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/mishmash/commands/sync/_inotify.py", line 112, in _main
unsonic.nicfit.net    |     self._inotify.remove_watch(str(path).encode(LOCAL_FS_ENCODING))
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/inotify/adapters.py", line 90, in remove_watch
unsonic.nicfit.net    |     inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)
unsonic.nicfit.net    |   File "/unsonic/lib/python3.6/site-packages/inotify/calls.py", line 35, in _check_nonnegative
unsonic.nicfit.net    |     (result,))
unsonic.nicfit.net    | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)

```

**Comment by nicfit** [comment]
Fixed up but inotify bit rot and seems to be working well. True reproducing this and was not able. Reopen if you have a method for reproducing.
