### ISSUE TITLE
Exception on "mishmash help info"

### ISSUE THREAD

**Issue by redshodan** [nicfit/MishMash#212]
(venv) baron@dib ~/src/unsonic $ ./build/venv/bin/mishmash help info
<mishmash:MainThread> [ERROR]: 'Namespace' object has no attribute 'command_func'
Traceback (most recent call last):
  File "/home/baron/src/unsonic/external/mishmash/mishmash/__main__.py", line 53, in main
    retval = args.command_func(args, args.config) or 0
AttributeError: 'Namespace' object has no attribute 'command_func'
General error:
Traceback (most recent call last):
  File "/home/baron/src/unsonic/external/mishmash/mishmash/__main__.py", line 53, in main
    retval = args.command_func(args, args.config) or 0
AttributeError: 'Namespace' object has no attribute 'command_func'

**Comment by nicfit** [comment]
Fixed in nicfit.py, https://github.com/nicfit/nicfit.py/commit/f971c21d8239ffd8ed6f72a434c5c230551236ba
