### ISSUE TITLE
TypeError: setFileScannerOpts() got an unexpected keyword argument 'default_recursive'

### ISSUE THREAD

**Issue by Mte90** [nicfit/MishMash#808]
```
$ mishmash sync ./Musica/
Traceback (most recent call last):
  File "/usr/local/bin/mishmash", line 5, in <module>
    from mishmash.__main__ import app
  File "/usr/local/lib/python3.9/dist-packages/mishmash/__main__.py", line 115, in <module>
    app = MishMash()
  File "/usr/local/lib/python3.9/dist-packages/mishmash/__main__.py", line 98, in __init__
    Command.loadCommandMap(subparsers=subs)
  File "/usr/local/lib/python3.9/dist-packages/nicfit/command.py", line 135, in loadCommandMap
    cmd = Cmd(subparsers=subparsers, **cmd_kwargs) \
  File "/usr/local/lib/python3.9/dist-packages/mishmash/commands/sync/sync.py", line 449, in __init__
    self.plugin = SyncPlugin(self.parser)
  File "/usr/local/lib/python3.9/dist-packages/mishmash/commands/sync/sync.py", line 50, in __init__
    eyed3.main.setFileScannerOpts(
TypeError: setFileScannerOpts() got an unexpected keyword argument 'default_recursive'
```

Also with `mishmash ./Musica/`

**Comment by nicfit** [comment]
Hi @Mte90 , thanks for reporting this. Sounds like the version of eyeD3 is out of date. That version of MishMash and eyeD3 are you using? You should try upgrading, `pip install -U eyeD3`.  I've also [bumped versions](https://github.com/nicfit/MishMash/commit/65795423498ab070e5dbab7b337d2d0ec6d6872e) in the main requirements.txt file, but have not tested these upgrades yet.

**Comment by Mte90** [comment]
I am using the debian package that is at 0.8.10, https://packages.debian.org/sid/eyed3

Switching to the package on pip instead from debian repository fixed it :-)
